apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: todo-taskapp:latest # Use your private repository name
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: dockerhub-secret # Reference the secret created for Docker Hub


# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=<your-docker-username> \
#   --docker-password=<your-docker-password> \
#   --docker-email=<your-email>

