apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app
spec:
  type: NodePort  # Change to LoadBalancer if using cloud or ClusterIP for internal access
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8081       # Port for external access
      targetPort: 8081 # Port on the container
      nodePort: 30081  # Port on the node (only for NodePort type)
